### ISSUE TITLE
có thể sort item "trang bị" mmoiventory

### ISSUE THREAD

**Issue by VuongVy** [Vinamc/towny#14]
- config mặc định của cái item để bật inventory là slot 9 (trên cùng bên trái)
- chest sort cục đó sẽ bay qua ô khác > out game vào lại thì slot 9 sẽ có thêm cục đó nếu slot đó đã có sẵn đồ thì item đó sẽ mất 
Giải pháp : chặn item "trang bị: có thể chest sort

**Comment by alexzvn** [comment]
Update [MMOInventory](https://github.com/Vinamc/MMOInventory) bản mới nhất.
